### ISSUE TITLE
ModuleNotFoundError: No module named 'statsmodels.tsa.statespace._representation'

### ISSUE THREAD

**Issue by xjeanyang414** [symbol-dapp/community#3]
I've encountered the aforementioned error while trying to 'import statsmodels.api as sm‘.
I can import statsmodels without any problems, but could not implement the 'import statsmodels.api' command. 
My python version is 3.8.5. 
I've tried various solutions suggested on the websites, but to no avail. I've been troubled by this issue for quite a while. 
Hope someone with the experience or expertise could help.

**Comment by aleixmorgadas** [comment]
wow, I got no idea what you are talking about :joy:

Open the issue in the actual repository, that's the only place people can help you. In case you don't find help, maybe you will need to dedicate some hours and make a contribution to that repository. Badly, that's how works Open Source Software when a project doesn't provide paid developer program support.

I close the issue here. I hope you can find a solution for your issue!
